# Generated by Django 3.2.16 on 2023-01-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0133_auto_20220919_2102'),
        ('judge', '0143_auto_20221229_0153'),
    ]

    operations = [
    ]
